export interface BugContext {
  testId: string;
  testTitle: string;
  testFile: string;
  status: "failed" | "timedOut" | "interrupted";
  errorMessage: string;
  errorStack?: string;
  durationMs: number;
  startedAt: string;
  observerArtifacts: {
    fsEventsJsonl?: string;
    mitmFlowPath?: string;
    perfSamplePath?: string;
    heapSnapshotPath?: string;
    logMatchesJsonl?: string;
  };
  env: {
    cursorVersion?: string;
    nodeVersion: string;
    platform: string;
    arch: string;
  };
}

/** Render a BugContext into the Markdown body defined by docs/BUG_REPORT_TEMPLATE.md. */
export function renderBugReport(ctx: BugContext): string {
  const artifacts = Object.entries(ctx.observerArtifacts)
    .filter(([, v]) => v != null)
    .map(([k, v]) => `- **${k}**: \`${v}\``)
    .join("\n");

  return `# Bug Report — ${ctx.testTitle}

**Test ID**: \`${ctx.testId}\`
**File**: \`${ctx.testFile}\`
**Status**: ${ctx.status}
**Started**: ${ctx.startedAt}
**Duration**: ${ctx.durationMs}ms

## Error

\`\`\`
${ctx.errorMessage}
\`\`\`

${ctx.errorStack ? `### Stack Trace\n\n\`\`\`\n${ctx.errorStack}\n\`\`\`\n` : ""}

## Observer Artifacts

${artifacts || "_No observer artifacts attached._"}

## Environment Snapshot

| Key | Value |
|---|---|
| Cursor version | ${ctx.env.cursorVersion ?? "unknown"} |
| Node.js | ${ctx.env.nodeVersion} |
| Platform | ${ctx.env.platform} |
| Arch | ${ctx.env.arch} |

---
_Auto-generated by cursor-pqe-harness playwright-bug-reporter._
`;
}
